### ISSUE TITLE
Produce RPM

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-vdsmfake#10]
# Motivation
To play with the ovirt CI echo-system and get the most of it, we should produce an RPM package.

- For such a small jar/war based project it's enough to use mvn or gradle tools. 
- Versioning schema - either use git tags, date, or the current mvn version scheme.
- RPM should be created under `exported-artifacts/` dir

# Tools in hand
-  [mvn rpm plugin](http://www.mojohaus.org/rpm-maven-plugin/) seems perfect for the job.
- gradle with rpm plugin
- make, autotools, like https://gerrit.ovirt.org/vdsm-jsonrpc-java 

# TODO
- An rpm artifact is published as a repo using repoman during OST run. It means it would be very easy to add fakevdsm to an OST suite

**Comment by ifireball** [comment]
There is another possible approach - just write a specfile and run `rpmbuild` from the automation scripts.

A minimal example could be seen here: https://gerrit.ovirt.org/gitweb?p=jenkins.git;a=blob;f=automation/check-patch.sh;#l84

**Comment by rgolangh** [comment]
It is an option indeed and a simple one, though the pom.xml one is simple as well.

## specfile
### pros
- known format for packagers
- zero effort from CI
### cons
- can't share the version parameter with pom.xml - require make's templates help

## mvn plugin
### pros
- known to devs
- share pom parameters and file structure knoledge
### cons
- might miss rpmbuild/specfile functionality (minor here)
- specfile definition is awkward and bit verbose in xml

**Comment by ifireball** [comment]
WRT sharing specfile version with `pom.xml`, it is certainly possible, and no templates are needed. See the example I linked to - it actually uses `git describe` to calculate the version and then passes it to `rpmbuild` with `--define`. If you can somehow pragmatically extract the version from `pom.xml` you can use it with the specfile.

**Comment by gregsheremeta** [comment]
+1 to just using a spec. Here's how we parse the version from package.json in JavaScript land:
https://gerrit.ovirt.org/#/c/72042/

You can use xmllint to do the same thing for a pom.

```
greg@greg-x1:~/projects/ovirt-engine(master↑1|…) $ echo "'$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)'"
'4.2.0-SNAPSHOT'
```
