### ISSUE TITLE
host add failure, architectureName

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-vdsmfake#11]
Using ovirt-vdsmfake master and ovirt-engine master, trying to setup new hosts, I got host add failure. Stack trace said because architectureName was null, so an enum couldn't be resolved. This tiny patch worked me around for now, but I have no idea if this is the proper way to fix it.

```
diff --git a/src/main/java/org/ovirt/vdsmfake/AppConfig.java b/src/main/java/org/ovirt/vdsmfake/AppConfig.java
index 99beee2..d29591f 100644
--- a/src/main/java/org/ovirt/vdsmfake/AppConfig.java
+++ b/src/main/java/org/ovirt/vdsmfake/AppConfig.java
@@ -188,7 +188,8 @@ public class AppConfig {
     }
 
     public ArchitectureType getArchitectureType() {
-        return ArchitectureType.valueOf(architectureType);
+        return architectureType != null ? ArchitectureType.valueOf(architectureType) :
+                ArchitectureType.X86_64;
     }
 
     public void setArchitectureType(String architectureType) {
```

**Comment by rgolangh** [comment]
Thanks @gregsheremeta . Can you please post a patch to gerrit?. It might have been me who broke it during my last changes. Must add unit and integration tests.

**Comment by mrsiano** [comment]
+1 I faced it as well.

**Comment by gregsheremeta** [comment]
https://gerrit.ovirt.org/#/c/73850/
