### ISSUE TITLE
Port collision with ovirt-imageio-daemon

### ISSUE THREAD

**Issue by pcbailey** [oVirt/ovirt-vdsmfake#15]
I had issues running vdsmfake due to a port collision with ovirt-imageio-daemon. I know the port can be configured to something else, but I suggest we change the default port to avoid this collision in the future.

**Comment by rgolangh** [comment]
@mwperina @jelkosz @pcbailey @gregsheremeta @rmohr
+1 Suggestion for the new port number for this minimal web interface?
Maybe still stay at the http range - 8081, 9090? or go with an offset, like 64321?

**Comment by pcbailey** [comment]
In my opinion, those in the 80XX and 90XX ranges get used very frequently, increasing the chance of collision. For instance, the Cockpit development instance uses 9090. My preference would be for the offset.

**Comment by mrsiano** [comment]
the port collision was for 8080 ? or the vdsm port 54321 ?

**Comment by pcbailey** [comment]
The collision was for port 54322.

**Comment by mrsiano** [comment]
hmmm, it;s the old port for vdsm xmlrpc,

can you share how you run the vdsmfake (command line) and all ports related
args from applicaion.conf ?

**Comment by pcbailey** [comment]
I run 'mvn clean jetty:run'. The only port that I see in application.conf is the one for the JSON RPC port, which is set to 54321.

**Comment by rmohr** [comment]
I would suggest to not start the xmlrpc backend anymore and add a switch which allows starting the old xmrpc instead of jsonrpc. Then we just need port 54321, which  is what engine expects.

**Comment by gregsheremeta** [comment]
I haven't run into this collision, but my Jetty also tells me it's using 54322:

```
mvn clean jetty:run
<snip>
[INFO] --- jetty-maven-plugin:9.3.7.v20160115:run (default-cli) @ vdsmfake_rpc ---
[INFO] Logging initialized @3356ms
[INFO] Configuring Jetty for project: vdsmfake Maven Webapp
[INFO] webAppSourceDirectory not set. Trying src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /home/greg/projects/ovirt-vdsmfake/target/classes
[INFO] Context path = /
[INFO] Tmp directory = /home/greg/projects/ovirt-vdsmfake/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:///home/greg/projects/ovirt-vdsmfake/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /home/greg/projects/ovirt-vdsmfake/src/main/webapp
[INFO] jetty-9.3.7.v20160115
Application initialized.
[INFO] Started o.e.j.m.p.JettyWebAppContext@4e1a46fb{/,file:///home/greg/projects/ovirt-vdsmfake/src/main/webapp/,AVAILABLE}{file:///home/greg/projects/ovirt-vdsmfake/src/main/webapp/}
[INFO] Started ServerConnector@1bf14704{HTTP/1.1,[http/1.1]}{0.0.0.0:54322}
[INFO] Started @20349ms
[INFO] Started Jetty Server
```

**Comment by rmohr** [comment]
> I would suggest to not start the xmlrpc backend anymore and add a switch which allows starting the old xmrpc instead of jsonrpc. Then we just need port 54321, which is what engine expects.


Oh forget my comment xmlrpc is already removed by @rgolangh.

**Comment by rmohr** [comment]
What I would definitely do, is binding the servlets to the starndard jetty port, so that you can override it. At least as a java developer I would expect, taht I can do something like `mvn -Djetty.http.port=9999 jetty:run` to let the servlets listen somewhere else ...

For me personally also taking `8081` (is that the next after development evirt-engine?) would be fine.

**Comment by rgolangh** [comment]
@rmohr see latest patchset under topic wildfly-swarm. we would still have of course `-Dswarm.http.port`

+1 for 8081
