### ISSUE TITLE
Cannot start daemon after the swarm inclusion - ClassNotFound

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-vdsmfake#18]
`mvn wildfly-swarm:run` results in:

```
[ERROR] Failed to execute goal org.wildfly.swarm:wildfly-swarm-plugin:2017.2.0:run (default-cli) on project vdsmfake_rpc: Execution default-cli of goal org.wildfly.swarm:wildfly-swarm-plugin:2017.2.0:run failed: A required class was missing while executing org.wildfly.swarm:wildfly-swarm-plugin:2017.2.0:run: Lorg/eclipse/aether/impl/ArtifactResolver;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.wildfly.swarm:wildfly-swarm-plugin:2017.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/msivak/.m2/repository/org/wildfly/swarm/wildfly-swarm-plugin/2017.2.0/wildfly-swarm-plugin-2017.2.0.jar
[ERROR] urls[1] = file:/home/msivak/.m2/repository/org/wildfly/swarm/fraction-list/2017.2.0/fraction-list-2017.2.0.jar
[ERROR] urls[2] = file:/home/msivak/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4.jar
[ERROR] urls[3] = file:/home/msivak/.m2/repository/org/wildfly/swarm/tools/2017.2.0/tools-2017.2.0.jar
[ERROR] urls[4] = file:/home/msivak/.m2/repository/org/wildfly/swarm/bootstrap/2017.2.0/bootstrap-2017.2.0.jar
[ERROR] urls[5] = file:/home/msivak/.m2/repository/org/jboss/modules/jboss-modules/1.5.2.Final/jboss-modules-1.5.2.Final.jar
[ERROR] urls[6] = file:/home/msivak/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
[ERROR] urls[7] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-api/1.2.6/shrinkwrap-api-1.2.6.jar
[ERROR] urls[8] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-spi/1.2.6/shrinkwrap-spi-1.2.6.jar
[ERROR] urls[9] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/shrinkwrap-impl-base/1.2.6/shrinkwrap-impl-base-1.2.6.jar
[ERROR] urls[10] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-jboss/2.0.0-alpha-9/shrinkwrap-descriptors-api-jboss-2.0.0-alpha-9.jar
[ERROR] urls[11] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-javaee/2.0.0-alpha-9/shrinkwrap-descriptors-api-javaee-2.0.0-alpha-9.jar
[ERROR] urls[12] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-api-base/2.0.0-alpha-9/shrinkwrap-descriptors-api-base-2.0.0-alpha-9.jar
[ERROR] urls[13] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-jboss/2.0.0-alpha-9/shrinkwrap-descriptors-impl-jboss-2.0.0-alpha-9.jar
[ERROR] urls[14] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-javaee/2.0.0-alpha-9/shrinkwrap-descriptors-impl-javaee-2.0.0-alpha-9.jar
[ERROR] urls[15] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-impl-base/2.0.0-alpha-9/shrinkwrap-descriptors-impl-base-2.0.0-alpha-9.jar
[ERROR] urls[16] = file:/home/msivak/.m2/repository/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-spi/2.0.0-alpha-9/shrinkwrap-descriptors-spi-2.0.0-alpha-9.jar
[ERROR] urls[17] = file:/home/msivak/.m2/repository/org/ow2/asm/asm-all/5.0.4/asm-all-5.0.4.jar
[ERROR] urls[18] = file:/home/msivak/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[19] = file:/home/msivak/.m2/repository/net/lingala/zip4j/zip4j/1.3.2/zip4j-1.3.2.jar
[ERROR] urls[20] = file:/home/msivak/.m2/repository/org/wildfly/swarm/spi/2017.2.0/spi-2017.2.0.jar
[ERROR] urls[21] = file:/home/msivak/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[22] = file:/home/msivak/.m2/repository/org/eclipse/aether/aether-util/1.0.0.v20140518/aether-util-1.0.0.v20140518.jar
[ERROR] urls[23] = file:/home/msivak/.m2/repository/org/eclipse/aether/aether-api/1.0.0.v20140518/aether-api-1.0.0.v20140518.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.eclipse.aether.impl.ArtifactResolver
```

**Comment by rgolangh** [comment]
@MarSik what maven version are you using? it works fine under 3.3.9

**Comment by rgolangh** [comment]
Wildfly swarm minimum maven version is 3.2.1 according to - 
https://github.com/wildfly-swarm/wildfly-swarm/blob/master/pom.xml#L118

**Comment by MarSik** [comment]
Well that might be an issue. The only maven available in CentOS 7 repositories is 3.0.5.

**Comment by rgolangh** [comment]
Try installing centos software collection 'centos-release-scl' it has mvn 3.3

**Comment by MarSik** [comment]
I already have better maven locally, but I guess this requirement should be documented visibly.

**Comment by rgolangh** [comment]
What I'm going to do in the Dockerfile is something like:

```
yum install -y centos-release-scl 
yum install -y rh-maven33
scl enable rh-maven33 "mvn clean package"
...
```

**Comment by MarSik** [comment]
Btw, I still get the following even when using the right maven. Hosts look online, but a VM can't "migrate", because the engine thinks it still runs on the original host.

ERROR [jsonrpcserver-pool-26] (JsonRpcServer.java:164) - Failure in processing request
java.lang.NoClassDefFoundError: Could not initialize class org.ovirt.vdsmfake.service.VMInfoService
	at org.ovirt.vdsmfake.service.VMService.fillVmStatsMap(VMService.java:402)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.ovirt.vdsmfake.service.VMService.getAllVmStats(VMService.java:520)
	at org.ovirt.vdsmfake.rpc.Api.getAllVmStats(Api.java:120)
	at org.ovirt.vdsmfake.rpc.json.commands.GetAllVmStatsCommand.activateApi(GetAllVmStatsCommand.java:17)
	at org.ovirt.vdsmfake.rpc.json.commands.JsonCommand.run(JsonCommand.java:35)
	at org.ovirt.vdsmfake.rpc.json.DefaultCommandExecutor.process(DefaultCommandExecutor.java:16)
	at org.ovirt.vdsmfake.rpc.json.CommandExecutor.execute(CommandExecutor.java:17)
	at org.ovirt.vdsmfake.rpc.json.JsonRpcServer$MessageHandler.run(JsonRpcServer.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rgolangh** [comment]
Did you follow all the db configuration steps on the README?

**Comment by MarSik** [comment]
I am using host name identifier if you are asking that.

Martin

**Comment by rgolangh** [comment]
@MarSik please open a new issue with the exect problem
