### ISSUE TITLE
Avoid mirroring resources.

### ISSUE THREAD

**Issue by mrsiano** [oVirt/ovirt-vdsmfake#24]
We should use single resources dir for both tests and actual app resources.

I've been faced some failure on unit tests regarding that problem.
as workaround we have to mirroring the applicaion.conf file

issue description:
- I've added a new conf to the applicaion conf file.
- I've complied the project.
- the unit test failed beacuse the applicaion.conf was pointed to wrong file <maindir>/test/resources/application.conf instead of "<maindir>/src/java/resources/applicaion.conf

adding 
@rgolangh
@pkliczewski

**Comment by sandrobonazzola** [comment]
This project is not maintained anymore, closing.
