### ISSUE TITLE
adapt the ipGenerator for CDI

### ISSUE THREAD

**Issue by mrsiano** [oVirt/ovirt-vdsmfake#25]
In continuing to https://gerrit.ovirt.org/#/c/75031/11/src/main/java/org/ovirt/vdsmfake/domain/VM.java@148

We should adapt \ improve the ipGenerator for CDI by a new PR.

benefits:
- nicer and cleaner code.
- cdi features.

@rgolangh @pkliczewski please review

**Comment by sandrobonazzola** [comment]
This project is not maintained anymore, closing.
