### ISSUE TITLE
Rework the getUuid() method

### ISSUE THREAD

**Issue by mrsiano** [oVirt/ovirt-vdsmfake#26]
In continuing to https://gerrit.ovirt.org/#/c/75031/11/src/main/java/org/ovirt/vdsmfake/service/AbstractService.java@a128

we should remove that function and use UUID class directly, but in some cases the current method is nicer, also since we use it multiple times it's nice to have it via method.

@rgolangh

**Comment by sandrobonazzola** [comment]
This project is not maintained anymore, closing.
