### ISSUE TITLE
Error while executing action Add Disk to VM: General Exception

### ISSUE THREAD

**Issue by tenstormavi** [oVirt/ovirt-vdsmfake#27]
I have set up ovirt-engine for testing purpose and, I am using ovirt-vdsmfake to provision host and vms on that ovirt-engine. But I am facing an error while creating a disk. 

I have provision 10 hosts, all are up with their own local storage. And when I am trying to add a disk to the disk section, error popups like "**Error while executing action Add Disk to VM: General Exception**". I saw the logs, thought of some permission error, checked that but still this error is coming.

Can somebody provide some input on it?

**Comment by mykaul** [comment]
1. I suggest using the users mailing list of oVirt to ask questions.
2. I suggest you use Lago and ovirt-system-tests (http://ovirt-system-tests.readthedocs.io/en/latest/) to perform the tests. Much more reliable.

**Comment by h4xr** [comment]
@mykaul 
We have a use case which I am not sure will work out with ovirt-system-tests and Lago project and hence we were looking for ovirt-vdsmfake.

We are trying to setup simulated virtual machines by mocking the Ovirt API through the use of vdsm-fake. The number of VMs we are trying to add to Ovirt is more than 2k distributed across various data centers and clusters. But running these VM's on hosts will require a huge amount of hardware resources which is not feasible for us to provide.

Adding on to this, we really don't need to do any operation inside the virtual machines, for which we will require VMs which have a real operating system installed on them for any task. All we need is a set of VMs inside Ovirt which Ovirt thinks are real in nature. This Ovirt instance will then be added to ManageIQ to test the amount of load the ManageIQ API can take up.

Going by the docs, If I understood them correctly, ovirt-systems-test utilizes Lago to create real Virtual machines which is not something we intend to do. Please let me know, If my understanding is incorrect and ovirt-system-tests can add simulated virtual machines to Ovirt.

This is something, which ovirt-vdsmfake is able to do easily except for the errors as mentioned in the first comment of this issue.

**Comment by mykaul** [comment]
@h4xr - I understand the use case now. Please consult with RHV QE on how they test with 2K VMs. We are not maintaining ovirt-vdsmfake anymore. If it works or someone fixes it - great.
