### ISSUE TITLE
Use proper configuration facility

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-vdsmfake#5]
A simulation application like vdsmfake needs flexible configuration facade to tweak the simulation for every need, with ease, preferably with ability to runtime reload support. Having parts of the config in the web.xml combined with Java properties is weak and simply leads to spagethi code. 

App usages:
- configure internal service details - ports, certificate, N of threads, etc,
- configure simulation - shift hardcoded simulation properties with files - e.g every call to GetVdsCaps responde from a proper configuration branch like mem, architecture, cpuType

There are handful of FOSS solution out-there there that support most of these:
- small footprint and dependency graph
- files -  .properties, json, hocon
- overloads
- imports
- Env variables
- variable interpolation 
- Java class variables binding to config items
- reload strategies - (some libraries supply it, some supply API to implement it)

I find https://github.com/typesafehub/config to be the most promising, as well as https://github.com/lviggiano/owner and https://github.com/cfg4j/cfg4j

**Comment by gregsheremeta** [comment]
Nice patch!

**Comment by rgolangh** [comment]
Thanks! to be continued with all of the hardcoded values out to files. I find https://github.com/typesafehub/config an excellent solution. Would consider that for ovirt/ovirt-engine as well (luckily vdsmfake is a perfect project to experience with toys :) )

We're missing the reload support - from what I see, it should be few lines of code. Will open an issue on it
