### ISSUE TITLE
Fix event sending

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-vdsmfake#8]
Currently event sending doesn't work. Essentially it is publishing the event on the wrong Q name - should be `jms.queue.events` instead of `jms.queue.messages`

**Comment by rgolangh** [comment]
@maorlipchuk fixed this.

**Comment by rgolangh** [comment]
@oVirt/admins please add @maorlipchuk to ovirt organization

**Comment by vinzenz** [comment]
@rgolangh done
